### ISSUE TITLE
realize（が依存しているurfave/cli）のgo getの失敗を回避

### ISSUE THREAD

**Issue by itohiro73** [keitakn/golang-grpc-server#23]
# Doneの定義
- realize のgo getに成功する事

# 変更点概要

`./scripts/docker-compose-up.sh` を走らせると下記のようなエラーが出る。
```
go get: gopkg.in/urfave/cli.v2@v2.2.0: parsing go.mod:
	module declares its path as: github.com/urfave/cli/v2
	        but was required as: gopkg.in/urfave/cli.v2
```

こちらは [oxequa/realize/issues/269](https://github.com/oxequa/realize/issues/269) に記載の通り `GO111MODULE=off go get github.com/oxequa/realize`とすることで回避できる。

また、[oxequa/realize/issues/253](https://github.com/oxequa/realize/issues/253), [nekochans/portfolio-backend/issues/11](https://github.com/nekochans/portfolio-backend/issues/11) で議論されていた回避策は現時点ではもう必要ないようなので削除。

```
go get gopkg.in/urfave/cli.v2@master && \
```

## 技術的変更点概要
```
[hiroshi@MacBook-Pro]# git diff           [/Users/hiroshi/Development/src/github.com/itohiro73/golang-grpc-server]
diff --git a/build/package/docker/grpc/Dockerfile b/build/package/docker/grpc/Dockerfile
index b685317..188289c 100644
--- a/build/package/docker/grpc/Dockerfile
+++ b/build/package/docker/grpc/Dockerfile
@@ -29,8 +29,7 @@ COPY . .
 
 RUN set -eux && \
   go build -o golang-grpc-server ./cmd/grpc/main.go && \
-  go get gopkg.in/urfave/cli.v2@master && \
-  go get github.com/oxequa/realize && \
+  GO111MODULE=off go get github.com/oxequa/realize && \
   go get -u github.com/go-delve/delve/cmd/dlv && \
   go build -o /go/bin/dlv github.com/go-delve/delve/cmd/dlv
```

**Comment by itohiro73** [comment]
airに対応する手前のいったんの繋ぎとして 🙏

**Comment by itohiro73** [comment]
と思ったけどairに対応した方が手っ取り早そうな気がしたのでこちらcloseします。お目汚し失礼しました 🙇

**Comment by keitakn** [comment]
@itohiro73 issue作成ありがとうございます👍

>と思ったけどairに対応した方が手っ取り早そうな気がしたので

そうなんですよね、、自分も `realize` のメンテナンスが止まっているのが気になって別プロジェクトで `air` に乗り換えちゃいました:sweat_smile:

`air` はGItHubのスター数とかはまだ少ないですが、結構有名なGoのコントリビューターの方が何名かコントリビュートされていたので、 `realize` ポジションの第一候補かなって思っています！
